#!/usr/bin/env bash
source ./definitions.bash
shopt -u extglob

SRC_FILE=$1
DBG_FILE=/tmp/$(basename $1).bdb

if [[ $(head -1 $SRC_FILE | awk '/^#!/') ]]; then
    start_line=1
else
    start_line=0
fi

omit_begin
flush_buf

for ((i="$start_line"; i<$(wc -l $SRC_FILE | cut -d ' ' -f 1); )); do
    show_prompt_string
    read cmd
    case "$cmd" in
        p)
            head -$i $SRC_FILE
            ;;
        b*)
            buf_action=$(show_cmd_args b)
            if [[ -z $buf_action ]]; then
                display_buf
            else
                for action in $buf_action; do
                    case $action in
                        d)
                            display_buf
                            ;;
                        e)
                            bash -c "$buf"
                            ;;
                        f)
                            flush_buf
                            ;;
                        *)
                            show_cmd_err
                    esac
                done
            fi
            ;;
        n*)
            next_actions=$(show_cmd_args n)
            ((i++))
            line=$(fetch_src_line $i)
            omit_end_reposition
            echo "$line" >> $DBG_FILE
            show_src_line $i "$line"
            if [[ -z $next_actions ]]; then
                increment_buf "$line"
            else
                for action in $next_actions; do
                    case $action in
                        w|"")
                            increment_buf "$line"
                            ;;
                        e)
                            bash $DBG_FILE
                            ;;
                        *)
                            show_cmd_err
                    esac
                done
            fi
            ;;
        q)
            break
            ;;
        h)
            show_cmd_help
            ;;
        d*)
            vars=$(show_cmd_args d)
            (
            source $DBG_FILE
            for var in $vars; do
                echo "$var: ${!var}"
            done
            )
            ;;
        *)
            show_cmd_err
            ;;
    esac
done

exit 0
