#!/usr/bin/env bash

SRC_FILE=$1
DBG_FILE=/tmp/$(basename $1).bdb

omit_begin() {
    printf "{ :\n" > $DBG_FILE
}

omit_end_reposition() {
    sed -i '/^} &>\/dev\/null$/d' $DBG_FILE
    printf "} &>/dev/null\n" >> $DBG_FILE
}

fetch_src_line() {
    line=$(head -$i $SRC_FILE | tail -1)
}

show_src_line() {
    printf "\033[032m%d\t%s\033[m\n" $i "$line"
}

show_prompt_string() {
    printf "\033[33m>>>\033[m "
}

show_cmd_err() {
    printf "\033[31mInvalid command. Enter h for help.\n\033[m"
}

show_cmd_help() {
    printf "\033[34mAvailable commands:
p : print cumulative file
n : execute next command
q : quit
\033[m"
}

if [[ $(head -1 $SRC_FILE | awk '/^#!/') ]]; then
    start_line=1
else
    start_line=0
fi

for ((i="$start_line"; i<$(wc -l $SRC_FILE | cut -d ' ' -f 1); )); do
    show_prompt_string
    read cmd
    case "$cmd" in
        p)
            head -$i $SRC_FILE
            ;;
        n)
            ((i++))
            fetch_src_line
            omit_end_reposition
            show_src_line
            bash $DBG_FILE
            ;;
        q)
            break
            ;;
        h)
            show_cmd_help
            ;;
        *)
            show_cmd_err
            ;;
    esac
done

